baseURL = "https://naos-atelier.netlify.com/"
languageCode = "fr-be"
title = "Naos Atelier"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
    description = "Du mobilier contemporain conçu et réalisé « sur mesure » et surtout « à la mesure » de l’environnement de chaque personne afin d’y intégrer au mieux l’objet ou l’aménagement."
